### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by nkleban** [layerhq/Atlas-Android-Messenger#27]
Null pointer exception when i'm trying to send new message (or whatever action that floating button provides)

FATAL EXCEPTION: main
                                                                                  Process: com.layer.messenger.providerdemo, PID: 14013
                                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'com.layer.sdk.messaging.Metadata com.layer.sdk.messaging.Conversation.getMetadata()' on a null object reference
                                                                                      at com.layer.atlas.util.Util.getConversationMetadataTitle(Util.java:109)
                                                                                      at com.layer.atlas.util.Util.getConversationTitle(Util.java:92)
                                                                                      at com.layer.messenger.MessagesListActivity.setTitle(MessagesListActivity.java:256)
                                                                                      at com.layer.messenger.MessagesListActivity$1.onEditorAction(MessagesListActivity.java:143)
                                                                                      at android.widget.TextView.onEditorAction(TextView.java:4777)
                                                                                      at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:139)
                                                                                      at android.view.inputmethod.InputConnectionWrapper.performEditorAction(InputConnectionWrapper.java:98)
                                                                                      at com.layer.atlas.util.views.EmptyDelEditText$EmptyDelInputConnection.performEditorAction(EmptyDelEditText.java:45)
                                                                                      at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:304)
                                                                                      at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:224)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by abeemukthees** [comment]
I'm also facing the same issue

**Comment by jtse-handy** [comment]
I got one step further. I clicked the FAB, got to a screen, typed a message, hit enter, and NPE. 

Apparently, the conversation is `null`

**Comment by romainbenmansour** [comment]
Same issue here. Did someone manage to fix it somehow ?

**Comment by amsibsam** [comment]
yes im facing this issue too, with null conversation

**Comment by roidnishikawa** [comment]
See last part of onCreate method in MessageListActivity.java.
Below code is creating conversation, and it seems the creation is only on there in whole code.

conversation = getLayerClient().newConversationWithUserIds(new ConversationOptions().distinct(true), participantIds);

In normal way, the participantIds should be null, and conversation will not be created.
So you need make participantIds before that code like,

String[] participantIds = {"people1", "people2", "people3"};

The code runs normally then.

**Comment by thecombatwombat** [comment]
A conversation must be created with valid participant Identities. Failing that, you're going to see the issue above. 

This is expected behavior. If you'd like to see a change made to that, please feel free to make a pull request, and we're happy to discuss the specific changes you propose.

Thanks!
