### ISSUE TITLE
IOS user not working In Android.

### ISSUE THREAD

**Issue by arpandesai** [layerhq/Atlas-Android-Messenger#40]
I am getting proper identity identity_token  

FATAL EXCEPTION: AsyncTask #3
                                                                          
                                                                          java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                              at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                              at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                              at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                              at java.lang.Thread.run(Thread.java:818)
                                                                           Caused by: java.lang.IllegalArgumentException: Invalid URI: layer:///identities/
                                                                              at com.layer.sdk.lsdka.lsdkd.m.b(LayerUri.java:184)
                                                                              at com.layer.sdk.lsdka.lsdkd.f.c(ChangeableCache.java:557)
                                                                              at com.layer.sdk.lsdka.lsdkd.f.a(ChangeableCache.java:359)
                                                                              at com.layer.sdk.lsdka.lsdkd.f.a(ChangeableCache.java:395)
                                                                              at com.layer.sdk.lsdka.lsdkh.c.a(IdentityQueryRepository.java:38)
                                                                              at com.layer.sdk.lsdka.lsdkh.g.a(QueryRepository.java:62)
                                                                              at com.layer.sdk.lsdka.a.executeQuery(LayerClientImpl.java:2943)
                                                                              at com.layer.atlas.AtlasAddressBar$IdentityFetcher$1.doInBackground(AtlasAddressBar.java:484)
                                                                              at com.layer.atlas.AtlasAddressBar$IdentityFetcher$1.doInBackground(AtlasAddressBar.java:480)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by thecombatwombat** [comment]
If you see the log above
`Caused by: java.lang.IllegalArgumentException: Invalid URI: layer:///identities/` 

it is clear that an incomplete/invalid Identity is being passed in.
