### ISSUE TITLE
Not able to send an image from chat using 'Gallery' attachment option

### ISSUE THREAD

**Issue by sahil0026** [layerhq/Atlas-Android-Messenger#7]
Hi, 

When I click on the 'Gallery' option in attachment menu, I get two choices in my android device to select a photo from. One from Gallery app and Another from Photos app by Google. If I select Gallery and select any photo, it works fine. But if I choose Photos and select any photo from there, the app crashes with the following error message.

01-11 10:50:49.782 5375-5375/com.layer.messenger.providerdemo D/AndroidRuntime: Shutting down VM
01-11 10:50:49.783 5375-5375/com.layer.messenger.providerdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.layer.messenger.providerdemo, PID: 5375
                                                                                java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=47001, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/0/1/mediaKey:/AF1QipNXGILSRFPlLOSKYqqL3kRn4zfiZmfh5UeSZRuV/ACTUAL/1377402969 flg=0x1 (has clip) }} to activity {com.layer.messenger.providerdemo/com.layer.messenger.MessagesListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3607)
                                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3650)
                                                                                    at android.app.ActivityThread.access$1400(ActivityThread.java:154)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1370)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                                    at java.io.File.fixSlashes(File.java:185)
                                                                                    at java.io.File.<init>(File.java:134)
                                                                                    at com.layer.atlas.messagetypes.threepartimage.ThreePartImageUtils.newThreePartImageMessage(ThreePartImageUtils.java:56)
                                                                                    at com.layer.atlas.messagetypes.threepartimage.GallerySender.onActivityResult(GallerySender.java:51)
                                                                                    at com.layer.atlas.AtlasMessageComposer.onActivityResult(AtlasMessageComposer.java:230)
                                                                                    at com.layer.messenger.MessagesListActivity.onActivityResult(MessagesListActivity.java:298)
                                                                                    at android.app.Activity.dispatchActivityResult(Activity.java:6192)
                                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3603)
                                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3650) 
                                                                                    at android.app.ActivityThread.access$1400(ActivityThread.java:154) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1370) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by sirvon** [comment]
@sahil0026  any discovery or movement with this issue?

**Comment by sahil0026** [comment]
@sirvon : nothing. no response from the layer staff.

**Comment by sjones94549** [comment]
We have yet to reproduce this; the Photos app works fine on a test device here.  What device, OS, etc. does this happen on?

**Comment by PratapOdedara** [comment]
This issue comes in comparatively new api levels greater then 21 coz that devices cant convert content uri to file so exception generated @sjones94549

**Comment by thecombatwombat** [comment]
The issue you've described pertains to an issue in [Atlas-Android0(https://github.com/layerhq/Atlas-Android). 

That was fixed [a while back](https://github.com/layerhq/Atlas-Android/pull/143). Please update to the latest version.
